[package]
name = "gd-props-defs"
version = "0.1.0"
edition = "2021"

[dependencies]
ron = "^0.8"
serde = { version = "^1", features = ["derive"] }
godot = { version = "0.1.*" }
rmp-serde = "^1.1.2"

[dev-dependencies]
gd-props = { path = "../gd-props" }