name: Crate tests

on:
  pull_request:
    branches:
      - master
      - development
  workflow_dispatch:

jobs:

  debug-test:
    uses: ./.github/workflows/reusable_tests.yaml
    with:
      godot-version: 4.2
      release: false

  release-test:
    needs: debug-test
    if: github.base_ref == 'master' || github.ref_name == 'master'
    uses: ./.github/workflows/reusable_tests.yaml
    with:
      godot-version: 4.2
      release: true


